### ISSUE TITLE
Upgrade to Python 3.x

### ISSUE THREAD

**Issue by nadirvardar** [rcook/swissarmyknife#1]
I love your product(Deduper), I am using it in my symbology NAS. Synology upgraded their python version to 3.x and I cannot use the product anymore. Is there a chance to upgrade the product to python 3.x ?

**Comment by rcook** [comment]
@nadirvardar : What errors do you see using Python 3.x? I just ran the script using Python 3.10.0 and it seemed to work fine, though I haven't exhaustively tested it.

**Comment by rcook** [comment]
@nadirvardar : Here's a related fix I just made: https://github.com/rcook/swissarmyknife/commit/e87aac4a4b07fcd9ab911fafb60d472a38a1f8c9. I don't have the time to exhaustively test the scripts, but this might get it closer to working on Python 3. If you can report specific errors (including repro steps) that you've encountered I can make more fixes.

**Comment by nadirvardar** [comment]
I see this error;
>> Removing Duplicates, /volume1/cloud/Dropbox/_books, 20:16:54
removeDuplicates -> /volume1/transmission/c/__others/python/swissarmyknife/deduper --no-dry-run --strategy keep-first --match sig --force /volume1/cloud/Dropbox/_books
Traceback (most recent call last):
  File "/volume1/transmission/c/__others/python/swissarmyknife/deduper", line 402, in <module>
    main()
  File "/volume1/transmission/c/__others/python/swissarmyknife/deduper", line 377, in main
    for k, v in sorted(vars(args).iteritems()):
AttributeError: 'dict' object has no attribute 'iteritems'

Thank you!!!

**Comment by nadirvardar** [comment]
Actually, I changed all ".iteritems()" to ".items()", it is working now ...

**Comment by rcook** [comment]
@nadirvardar : Thanks. I've made a similar change here. The code now uses `items` instead of `iteritems` and the `functools.cmp_to_key` adapter function. I hope this helps you make progress. Use at your own risk!

**Comment by nadirvardar** [comment]
The other thing is;
https://stackoverflow.com/questions/22490366/how-to-use-cmp-in-python-3

added;
def cmp(a, b):
    return (a > b) - (a < b)

to deduper..

Now it works;

removeDuplicates -> /volume1/transmission/c/__others/python/swissarmyknife/deduper --no-dry-run --strategy keep-first --match sig --force /volume1/cloud/Dropbox/_books
INFO:Argument: debug=False
INFO:Argument: dry_run=False
INFO:Argument: force=True
INFO:Argument: matcher=sig
INFO:Argument: progress=False
INFO:Argument: start_dir=/volume1/cloud/Dropbox/_books
INFO:Argument: strategy=keep-first
INFO:Argument: verbose=False
INFO:Deduplication started at 2022-01-25 20:59:15.401763
INFO:Finding duplicates using "sig" matcher
INFO:Size scan found 8186 candidate files
INFO:Signature scan found 1200 candidate files
INFO:Found 699 duplicate files occupying 4.6 GiB
INFO:Removing duplicates
INFO:Strategy "keep-first" deleted 699 files and freed 4.6 GiB
INFO:Deduplication finished at 2022-01-25 21:07:52.539644, elapsed time: 0:08:37.137881

**Comment by rcook** [comment]
Yes, my latest commit add `cmp` and uses `functools.cmp_to_key` to use this with `sorted`.

**Comment by nadirvardar** [comment]
It works now. Thank you so much!!!
